spring.application.name=webapp-2

# ==============================
# PostgreSQL接続設定
# ==============================

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/exam_training

spring.datasource.username=springuser

spring.datasource.password=${DB_PASSWORD}


# ==============================
# SQL初期化
# ==============================

# 既存のテーブルを誤って変更しないよう、いったん無効
spring.sql.init.mode=never


# ==============================
# MyBatis
# ==============================

logging.level.com.example.demo.repository=DEBUG